import type { Metadata } from "next";
import "./globals.css";
import { Karla } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Matthew Choi",
  description: "Generated by create next app",
};

const themeInitializerScript = `
(() => {
  try {
    const savedTheme = window.localStorage.getItem("theme");
    const systemPrefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const theme = savedTheme === "light" || savedTheme === "dark"
      ? savedTheme
      : (systemPrefersDark ? "dark" : "light");
    document.documentElement.dataset.theme = theme;
  } catch (_) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link
        rel="icon"
        href="/icon.ico"
        type="image/ico"
        sizes="96x96"
      />
      <script dangerouslySetInnerHTML={{ __html: themeInitializerScript }} />
      </head>
      <body className={karla.className}>
        {children}
      </body>
    </html>
  );
}
