import type { Metadata } from "next";
import "./globals.css";
import { Karla } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Matthew Choi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
        rel="icon"
        href="/icon.ico"
        type="image/ico"
        sizes="96x96"
      />
      </head>
      <body className={karla.className}>
        {children}
      </body>
    </html>
  );
}
